#### Consider the below code to answer further questions:
#### import numpy as np
#### list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
#### array_list = np.array(object = list_)

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a codeto print the data types of both the variables.

Yes, there is a difference in the data type of the list_ variable and the array_list variable. The list_ variable is a Python list containing string objects, whereas the array_list variable is a NumPy array containing string objects.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_)) # prints <class 'list'>
print(type(array_list)) # prints <class 'numpy.ndarray'>

<class 'list'>
<class 'numpy.ndarray'>


#### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of list_ elements
for element in list_:
    print(type(element))

# Print data type of array_list elements
print(array_list.dtype)


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<U1


#### Q3. Considering the following changes in the variable, array_list:
##### array_list = np.array(object = list_, dtype = int)
#### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_and arra_list.

Yes, there will be a difference in the data type of the elements present in list_ and array_list when the dtype parameter is set to int. The elements in list_ are strings, while the dtype parameter converts the elements in array_list to integers.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of list_ elements
for element in list_:
    print(type(element))

# Print data type of array_list elements
print(array_list.dtype)


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
int64


#### Consider the below code to answer further questions:
#### import numpy as np
#### num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
#### num_array = np.array(object = num_list)

#### Q4. Write a code to find the following characteristics of variable, num_array:
#### (i) shape
#### (ii) size

In [4]:
import numpy as np

# Create a 2D NumPy array
num_array = np.array([[1, 2, 3], [4, 5, 6]])

# Print the shape of the array
print("Shape of the array:", num_array.shape)

# Print the size of the array
print("Size of the array:", num_array.size)


Shape of the array: (2, 3)
Size of the array: 6


#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [5]:
import numpy as np

# Create a 3x3 NumPy array containing zeros only
zero_array = np.zeros((3, 3))

# Print the array
print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [6]:
import numpy as np

# Create a 5x5 identity matrix using the identity function
identity_matrix = np.identity(5)

# Print the matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
